name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: nimlang/nim
    steps:
    - uses: actions/checkout@v3
    - name: Build package
      run: nimble build -d:release -y
    - name: Get help
      run: ./spriterot --help